name: Attendance Automation
on:
  schedule:
    - cron: '0 10 * * 4' # Every Thursday at 10:00 UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  run-automation:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.1-jammy # Playwright's official container with browsers pre-installed
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      # No need to run 'npx playwright install chromium' because it's already in the container!
      - run: npm run attendance
        env:
          ATTENDANCE_LOGIN_USERNAME: ${{ secrets.ATTENDANCE_LOGIN_USERNAME }}
          ATTENDANCE_LOGIN_PASSWORD: ${{ secrets.ATTENDANCE_LOGIN_PASSWORD }}
